name: Seed Loop Cron

on:
  schedule:
    - cron: "0 0 * * *"  # every day 00:00 UTC
  workflow_dispatch:     # can also be run manually

jobs:
  seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run seeder
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python seed_loop.py
